theme: jekyll-theme-midnight
locale: en-US
title: "Effects of Online Learning Engagement Techniques for a College Stress Reduction Module"
description: "A GitHub site for my master's applied research project"
baseurl: /stressintervention
